# Generated by Django 2.2.3 on 2021-02-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Developer', 'Developer'), ('HR', 'HR'), ('Enginerr', 'Engineer')], max_length=50, null=True)),
                ('designation', models.CharField(choices=[('Senior', 'Senior Assosicate'), ('Intern', 'Intern'), ('Associate', 'Associate'), ('Software', 'Software')], max_length=50, null=True)),
            ],
        ),
    ]
