# Generated by Django 3.1.5 on 2021-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Developer', 'Developer'), ('HR', 'HR'), ('Enginerr', 'Engineer')], max_length=50, null=True)),
                ('designation', models.CharField(choices=[('Senior Assosicate', 'Senior Assosicate'), ('Intern', 'Intern'), ('Associate', 'Associate'), ('Software', 'Software')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='annoymoususer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('Intern', 'Intern'), ('Developer', 'Developer'), ('HR', 'HR'), ('Enginerr', 'Engineer')], max_length=50, null=True)),
                ('designation', models.CharField(choices=[('Senior Assosicate', 'Senior Assosicate'), ('Intern', 'Intern'), ('Associate', 'Associate'), ('Software', 'Software')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='auth',
            name='designation',
            field=models.CharField(choices=[('Senior Assosicate', 'Senior Assosicate'), ('Intern', 'Intern'), ('Associate', 'Associate'), ('Software', 'Software')], max_length=50, null=True),
        ),
    ]
