# Generated by Django 3.1.5 on 2021-02-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210204_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminuser',
            new_name='adminuser1',
        ),
    ]
